CREATE TABLE task_reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id BIGINT NOT NULL,
    reminder_type VARCHAR(32) NOT NULL,
    scheduled_for TIMESTAMPTZ NOT NULL,
    sent_at TIMESTAMPTZ,
    status VARCHAR(16) NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error_message VARCHAR(500),
    next_attempt_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_task_reminders_task
        FOREIGN KEY (task_id) REFERENCES tasks (id) ON DELETE CASCADE,
    CONSTRAINT uk_task_reminders_task_type UNIQUE (task_id, reminder_type),
    CONSTRAINT chk_task_reminders_type CHECK (
        reminder_type IN (
            'DEADLINE_24_HOURS',
            'DEADLINE_1_HOUR',
            'DEADLINE_REACHED'
        )
    ),
    CONSTRAINT chk_task_reminders_status CHECK (
        status IN ('PENDING', 'PROCESSING', 'SENT', 'FAILED', 'CANCELLED')
    ),
    CONSTRAINT chk_task_reminders_attempt_count CHECK (attempt_count >= 0)
);

CREATE INDEX idx_task_reminders_due
    ON task_reminders (status, next_attempt_at, scheduled_for);
CREATE INDEX idx_task_reminders_task ON task_reminders (task_id);
